

INSERT INTO ENDERECO(CEP, BAIRRO, CIDADE, COMPLEMENTO, LOGRADOURO, NUMERO, UF) VALUES(123, 'DFSKJ', 'FDKS', 'FJKDS', 'JFKSDL', 12, 'AS');

INSERT INTO MEDICOS(NOME, EMAIL, EH_ATIVO, CRM, ESPECIALIDADE, ENDERECO_CEP) VALUES('JFSDJKF', 'FJKDSJF', FALSE, 12, 'ORTOPEDIA', 123); 