

INSERT INTO ENDERECO(CEP, BAIRRO, CIDADE, COMPLEMENTO, LOGRADOURO, NUMERO, UF) VALUES(123, 'DFSKJ', 'FDKS', 'FJKDS', 'JFKSDL', 12, 'AS');

INSERT INTO MEDICOS(NOME, EMAIL, EH_ATIVO, CRM, ESPECIALIDADE, ENDERECO_CEP) VALUES('JFSDJKF', 'FJKDSJF', TRUE, 12, 'ORTOPEDIA', 123); 

INSERT INTO PACIENTES(NOME, EMAIL, EH_ATIVO, CPF, ENDERECO_CEP) VALUES('JFDJKF', 'FJKSJF', TRUE, 124, 123); 

INSERT INTO MEDICOS(NOME, EMAIL, TELEFONE, EH_ATIVO, CRM, ESPECIALIDADE, ENDERECO_CEP) VALUES('JFSDJKF', 'FJKDSJF', '12313', true, 43, 'ORTOPEDIA', null); 