

INSERT INTO MEDICOS(NOME, EMAIL, EH_ATIVO, CRM, ESPECIALIDADE, ENDERECO) VALUES('JFSDJKF', 'FJKDSJF', TRUE, 12, 'ORTOPEDIA', 'dsad'); 

INSERT INTO PACIENTES(NOME, EMAIL, EH_ATIVO, CPF, ENDERECO) VALUES('JFDJKF', 'FJKSJF', TRUE, 124, 'saddsa'); 

INSERT INTO MEDICOS(NOME, EMAIL, TELEFONE, EH_ATIVO, CRM, ESPECIALIDADE, ENDERECO) VALUES('JFSDJKF', 'FJKDSJF', '12313', true, 43, 'ORTOPEDIA', 'dasdas'); 
